version: 2.1

executors:
    databricks:
        docker:
            - image: databricksruntime/python-virtualenv:latest
        environment: 
            PYTHON_PATH: /databricks/python3/bin/python3
            PIP_PATH: /databricks/python3/bin/pip


jobs:
    build-and-test:
        executor: databricks
        working_directory: ~/test
        steps:
         - checkout
         - run:
            name: unittest
            command: |
                ${PIP_PATH} list
                ${PIP_PATH} install -r requirements.txt --quiet
                ${PYTHON_PATH} -m unittest discover -v             

workflows:
    main:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        only:
                            dev
                                                                                                                                        
