version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  codecov: codecov/codecov@1.1.1

executors:
  databricks:
    docker:
      #- image: databricksruntime/python-virtualenv:latest
      - image: mangohero1985/custom_databricks:3.7
    environment:
      PYTHON_PATH: /databricks/python3/bin/python3
      PIP_PATH: /databricks/python3/bin/pip
      COVERAGE_PATH: /databricks/python3/bin/coverage
      PYLINT_PATH: /databricks/python3/bin/pylint
      BLACK_PATH: /databricks/python3/bin/black

  python:
    docker:
      - image: circleci/python:3.7.5
    environment:
      DATABRICKS_HOST: https://supership.cloud.databricks.com
      DEPLOY_DIR: /user/weichang.chen@supership.jp/tmp/devops/

commands:
  install_databricks_cli:
    description: "install and configure databricks-cli"
    steps:
      - run:
          name: install databricks-cli
          command: |
            sudo python install databricks-cli


jobs:
  build-and-test:
    executor: databricks
    working_directory: ~/test
    steps:
      - checkout
      - run:
          name: install requirments
          command: |
            ${PIP_PATH} install --upgrade pip --quiet
            ${PIP_PATH} install -r requirements.txt --quiet
            ${PIP_PATH} list
      - run:
          name: code formatrer and syntax check
          command: |
            ${BLACK_PATH} ./*.py
      - run:
          name: unittest
          command: |
            ${COVERAGE_PATH} run -m unittest discover -v -s .
      - run:
          name: coverage check
          command: |
            ${COVERAGE_PATH} report -m --include=./*
            ${COVERAGE_PATH} html --include=./*
            ${COVERAGE_PATH} xml --include=./* -o htmlcov/coverage.xml
      - run:
          name: coding convention check
          command: |
            ${PYLINT_PATH} --output-format=parseable \
                           --disable=missing-docstring -rn \
                           --exit-zero \
                           --msg-template="{abspath}:{line}: [{msg_id}({symbol}), {obj}] {msg}" \
                           ./*.py > ./htmlcov/pylint.txt
      - store_artifacts:
          path: ./htmlcov
      - codecov/upload:
          file: ./htmlcov/coverage.xml
          flags: unittests
          token: ${CODECOV_TOKEN}

      - slack/status:
          mentions: "weichang.chen"
          success_message: ':circleci-pass: $CIRCLE_BRANCH passed \n:github: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH failed \n:github: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

  deploy:
    executor: python
    steps:
      - checkout
      - install_databricks_cli
      - run:
          name: deploy
          command: |
            databricks workspace delete -r $DEPLOY_DIR
            databricks workspace import_dir -e -o ./ $DEPLOY_DIR


workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - dev
                - master
      - deploy:
          filters:
            branches:
              only:
                - dev
                - master

                                                                                                                                        
