version: 2.1

executors:
    databricks:
        docker:
            - image：databricksruntime/standard:latest


jobs:
    build-and-test:
        executor: databricks
        working_directory: ~/test
        steps:
         - checkout
         - run:
            name: unittest
            command: |
                /databricks/conda/envs/dcs-minimal/bin/pip install -r requirements.txt
                /databricks/conda/envs/dcs-minimal/bin/python -m unittest discover -v
            

workflows:
    main:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        only:
                            dev
                                                                                                                                        