version: 2.1

executors:
    databricks:
        docker:
            - image: databricksruntime/standard:latest
        environment: 
            PYTHON_PATH: /databricks/conda/envs/dcs-minimal/bin/python3
            PIP_PATH: /databricks/conda/envs/dcs-minimal/bin/pip


jobs:
    build-and-test:
        executor: databricks
        working_directory: ~/test
        steps:
         - checkout
         - install-deps
         - run:
            name: unittest
            command: |
                ${PIP_PATH} list
                #${PIP_PATH} install -r requirements.txt
                ${PYTHON_PATH} -m unittest discover -v
            

workflows:
    main:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        only:
                            dev
                                                                                                                                        
